"""The hardware interface the brain is allowed to call (§3 of the guide).

This is a ``typing.Protocol`` -- a *structural* interface.  Any object that has
these methods (the simulator OR the real Kinesis driver) is a valid backend;
there is no base class to inherit.  The brain depends ONLY on this Protocol, so
the two implementations are perfectly interchangeable.

Axis is always an integer index: 0=X, 1=Y, 2=Z.  All positions/velocities are
in physical units (mm, mm/s, mm/s^2).

Contract note (fire-and-forget): ``move_to`` and ``home`` START motion and
return immediately.  Progress is observed by polling ``read_position`` /
``is_moving`` / ``is_homed``.  Clamping and sequencing are the brain's job, not
the backend's -- setters here command directly.
"""

from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class StageBackend(Protocol):
    # -- connection -------------------------------------------------------- #
    def open(self) -> None: ...
    def close(self) -> None: ...
    def idn(self) -> str: ...

    # -- motion (fire-and-forget) ----------------------------------------- #
    def home(self, axis: int) -> None: ...
    def is_homed(self, axis: int) -> bool: ...
    def move_to(self, axis: int, position: float) -> None: ...
    def is_moving(self, axis: int) -> bool: ...
    def stop(self, axis: int) -> None: ...
    def read_position(self, axis: int) -> float: ...

    # -- motion parameters ------------------------------------------------- #
    def set_velocity(self, axis: int, velocity: float) -> None: ...
    def read_velocity(self, axis: int) -> float: ...
    def set_acceleration(self, axis: int, acceleration: float) -> None: ...
    def read_acceleration(self, axis: int) -> float: ...
