"""The hardware interface the brain is allowed to call (§3 of the guide).

This is a ``typing.Protocol`` -- a *structural* interface.  Any object that has
these methods (the simulator OR the real Kinesis driver) is a valid backend;
there is no base class to inherit.  The brain depends ONLY on this Protocol, so
the two implementations are perfectly interchangeable.

Axis is always an integer index: 0=X, 1=Y, 2=Z.

The backend speaks the controller's NATIVE language: everything here is in
STEPS (position, targets) and step units (steps/s, steps/s^2, volts).  All
micrometre <-> step conversion is the brain's job, not the backend's, so this
interface stays a thin mirror of what the KIM101 actually does.

Contract note (fire-and-forget): ``move_to`` and ``move_by`` START motion and
return immediately.  Progress is observed by polling ``read_position`` /
``is_moving``.  There is no homing: piezo-inertia actuators are open-loop with
no limit switches, so a datum is defined by ``zero_counter`` (reset the step
count to 0 at the current physical position).
"""

from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class KimBackend(Protocol):
    # -- connection -------------------------------------------------------- #
    def open(self) -> None: ...
    def close(self) -> None: ...
    def idn(self) -> str: ...

    # -- motion (fire-and-forget, all in STEPS) --------------------------- #
    def move_to(self, axis: int, position_steps: int) -> None: ...
    def move_by(self, axis: int, delta_steps: int) -> None: ...
    def is_moving(self, axis: int) -> bool: ...
    def stop(self, axis: int) -> None: ...
    def read_position(self, axis: int) -> int: ...
    def zero_counter(self, axis: int) -> None: ...

    # -- drive parameters -------------------------------------------------- #
    def set_step_rate(self, axis: int, steps_per_sec: float) -> None: ...
    def read_step_rate(self, axis: int) -> float: ...
    def set_acceleration(self, axis: int, steps_per_sec2: float) -> None: ...
    def read_acceleration(self, axis: int) -> float: ...
    def set_voltage(self, axis: int, volts: float) -> None: ...
    def read_voltage(self, axis: int) -> float: ...
